name: telemed-ia-intelligent-agent-portal

services:
  intelligent-agent-portal:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    expose:
      - "80"
    networks:
      - platform

networks:
  platform:
    name: platform
    external: true